on: [push, pull_request]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v2
      with:
        version: latest
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
    
    - name: Install dependencies
      run: pnpm install

    - name: Install coveralls
      run: pnpm add coveralls
    
    - name: Run tests with coverage
      run: pnpm test:coverage
    
    - name: Upload coverage to Coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      run: |
        pnpm exec coveralls < coverage/lcov.info